### ISSUE TITLE
alphabetically sort rules

### ISSUE THREAD

**Issue by miquelmasrieramrf** [stefanosaittamrf/eslint-mrf#10]
does it make sense to you to sort the rules alphabetically?
I think it would make it easier to find/modify/remove and to follow along with the docs http://eslint.org/docs/rules/

**Comment by stefanosaittamrf** [comment]
To me yes! Even split them into the chunks as the docs does.

### Question

What you think about changing the file type from `.json` to `.js`, in this way we can put comments on it and test the integrity with ease.

### Ref

#14 

[Configuration File Formats](http://eslint.org/docs/user-guide/configuring#configuration-file-formats)
