### ISSUE TITLE
no-magic-numbers

### ISSUE THREAD

**Issue by miquelmasrieramrf** [stefanosaittamrf/eslint-mrf#7]
### Rule
 - [no magic numbers](http://eslint.org/docs/rules/no-magic-numbers)

### Discussion
it's pretty annoying, magic numbers should better be checked in the PRs
example
<img src="https://cloud.githubusercontent.com/assets/20967825/22026012/ca359526-dccf-11e6-9892-00ac78400c39.png" width="300px">

### Proposed change
remove  ```no-magic-numbers```

**Comment by stefanosaittamrf** [comment]
Agree with this since there are no option to avoid numbers into arrays.

**Comment by miquelmasrieramrf** [comment]
also in loops or in things like `if ( a.indexOf('b') !== -1)`

**Comment by stefanosaittamrf** [comment]
you can exclude some numbers, like 1 -1 0 that are the most used, but anyway is to bringing any value, the concept of magic number is more semantic than syntactic so job for PR reviewer.
