### ISSUE TITLE
sort-imports

### ISSUE THREAD

**Issue by miquelmasrieramrf** [stefanosaittamrf/eslint-mrf#8]
### Rule
 - [sort-imports](http://eslint.org/docs/rules/sort-imports)

### Discussion
The casing should be ignored, and maybe this rule could be removed, I personally prefer to sort the imports in the order that they are used.

### Proposed change

```json
  {
    "sort-imports": ["error", {"ignoreCase": false}]
  }
```  

### Reference

#4

**Comment by stefanosaittamrf** [comment]
Actually i prefer them sorted alphabetically, it's easy to find what you are looking for without thinking  too much.

In order to spot the dep i'm looking for "in the order that they are used" i have to first see how they are used, in the other case the only requirements is to know the alphabet
